/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uach.GUI;

import com.uach.xmlmanager.JDom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import org.jdom2.Content;
import org.jdom2.filter.Filters;

/**
 *
 * @author edgar
 */
public class EditElement extends javax.swing.JFrame {

    /**
     * Creates new form EditElement
     */
    JDom p = new JDom();
    public List<Content> elements = new ArrayList<Content>();
    public Integer cmbIndex;
    public Integer i = 0;
    public Boolean flag = false;

    public EditElement() {
        initComponents();
    }

    public EditElement(List<Content> elements) {
        initComponents();
        setElements(elements);
        if (!getElements().isEmpty()) {
            getElements().forEach((element) -> {
                cmbElementos.addItem(element.toString() + " " + i);
                i++;
            });
        }
        this.setLocationRelativeTo(null);
    }

    public void setElements(List<Content> elements) {
        this.elements = elements;
    }

    public List<Content> getElements() {
        return elements;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbElementos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaContent = new javax.swing.JTextArea();
        bntGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Editar elemento");

        cmbElementos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-" }));
        cmbElementos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbElementosItemStateChanged(evt);
            }
        });

        txaContent.setColumns(20);
        txaContent.setLineWrap(true);
        txaContent.setRows(5);
        jScrollPane1.setViewportView(txaContent);

        bntGuardar.setText("Guardar");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(cmbElementos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bntGuardar)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmbElementos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bntGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
        cmbIndex = cmbElementos.getSelectedIndex();
        p.setNodoPadre(p.getNode(p.getDocXML()
                .getDescendants(Filters.element()), cmbIndex - 1));
        p.getNodoPadre().removeContent();
        p.getNodoPadre().addContent(txaContent.getText());
        flag = true;
        this.dispose();
    }//GEN-LAST:event_bntGuardarActionPerformed

    private void cmbElementosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbElementosItemStateChanged
        cmbIndex = cmbElementos.getSelectedIndex();
        System.out.println(cmbIndex);
        if (cmbIndex > 0) {
            p.setNodoPadre(p.getNode(p.getDocXML()
                    .getDescendants(Filters.element()), cmbIndex - 1));
            txaContent.setText(p.getNodoPadre().getText());
        }
    }//GEN-LAST:event_cmbElementosItemStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntGuardar;
    private javax.swing.JComboBox<String> cmbElementos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaContent;
    // End of variables declaration//GEN-END:variables
}
